In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from numerical_checking import NumericalCheckingRecord
from jax import numpy as jnp, random

In [3]:
key1, key2, key3 = random.split(random.PRNGKey(0), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 11))))

In [4]:
tmp

(DeviceArray([[ 0.6303109 ,  1.432304  , -1.4815774 ,  0.4923746 ,
               -1.1934462 ,  0.1029949 ,  1.0404508 ,  0.7496347 ,
                1.5198213 , -0.45946267],
              [ 1.8907243 ,  0.33891958, -1.6513963 ,  2.025     ,
               -0.59403837, -1.3650762 ,  0.6576733 ,  0.10164347,
               -0.38275942, -0.2551205 ],
              [-0.64304477, -0.09750401,  0.53665197, -0.3927624 ,
                0.21680598,  2.7338872 , -0.5201809 , -1.4605844 ,
                1.0793773 , -0.8917047 ],
              [ 0.81454676, -0.12992854, -0.65803707, -1.5389702 ,
               -0.92621785,  0.6640493 ,  1.0109736 ,  1.383387  ,
               -1.193292  ,  0.01594991],
              [ 0.27041394,  2.3640893 ,  0.73086935,  0.8289051 ,
               -2.1422908 ,  1.2738072 ,  0.21341887, -1.4553308 ,
                0.89717144,  0.18064894]], dtype=float32),
 (DeviceArray([[ 0.08780523, -1.4772962 ,  0.23108286,  0.3828757 ,
                 0.42218092, -1.435

In [5]:
record = NumericalCheckingRecord(tmp)

In [7]:
record.save('test')

In [8]:
loaded_record = NumericalCheckingRecord.load('test')

In [9]:
loaded_record.data

(DeviceArray([[ 0.6303109 ,  1.432304  , -1.4815774 ,  0.4923746 ,
               -1.1934462 ,  0.1029949 ,  1.0404508 ,  0.7496347 ,
                1.5198213 , -0.45946267],
              [ 1.8907243 ,  0.33891958, -1.6513963 ,  2.025     ,
               -0.59403837, -1.3650762 ,  0.6576733 ,  0.10164347,
               -0.38275942, -0.2551205 ],
              [-0.64304477, -0.09750401,  0.53665197, -0.3927624 ,
                0.21680598,  2.7338872 , -0.5201809 , -1.4605844 ,
                1.0793773 , -0.8917047 ],
              [ 0.81454676, -0.12992854, -0.65803707, -1.5389702 ,
               -0.92621785,  0.6640493 ,  1.0109736 ,  1.383387  ,
               -1.193292  ,  0.01594991],
              [ 0.27041394,  2.3640893 ,  0.73086935,  0.8289051 ,
               -2.1422908 ,  1.2738072 ,  0.21341887, -1.4553308 ,
                0.89717144,  0.18064894]], dtype=float32),
 (DeviceArray([[ 0.08780523, -1.4772962 ,  0.23108286,  0.3828757 ,
                 0.42218092, -1.435

In [16]:
key1, key2, key3 = random.split(random.PRNGKey(0), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 11))))

print(loaded_record.check(tmp) == True)

True


In [17]:
key1, key2, key3 = random.split(random.PRNGKey(1), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 11))))

print(loaded_record.check(tmp) == True)


False


In [24]:
key1, key2, key3 = random.split(random.PRNGKey(0), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 12))))

print(loaded_record.check(tmp) == True)

TypeError: sub got incompatible shapes for broadcasting: (6, 9, 11), (6, 9, 12).

In [25]:
key1, key2, key3 = random.split(random.PRNGKey(0), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 11))))

print(record.check(tmp) == True)

True


In [26]:
key1, key2, key3 = random.split(random.PRNGKey(1), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 11))))

print(record.check(tmp) == True)


False


In [27]:
key1, key2, key3 = random.split(random.PRNGKey(0), num=3)
tmp = (random.normal(key1, (5, 10)), (random.normal(key2, (4, 8)), random.normal(key3, (6, 9, 12))))

print(record.check(tmp) == True)

TypeError: sub got incompatible shapes for broadcasting: (6, 9, 11), (6, 9, 12).